name: Build and Deploy

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: hogeun-app
  EKS_CLUSTER: hogeun-eks-cluster
  K8S_NAMESPACE: default

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # GitHub 저장소 Secrets으로 관리
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        run: |
          # SHA 태그와 latest 태그 동시에 푸시
          docker build -t ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} .
          docker tag ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
          docker push ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }} --all-tags

      - name: Update K8s Manifest
        run: |
          # deployment.yml 파일의 이미지 태그를 GitHub SHA로 업데이트
          sed -i "s|image:.*|image: ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}|" k8s/manifests/deployment.yml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add k8s/manifests/deployment.yml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push
