name: Build and Deploy

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: hogeun-app
  EKS_CLUSTER: hogeun-eks-cluster
  K8S_NAMESPACE: default

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write  # ECR 푸시를 위한 권한 추가

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        run: |
          docker build \
            -f didle/didle/Dockerfile \
            -t ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} \
            -t ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest \
            .
          docker push ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }} --all-tags

      - name: Update K8s Manifest
        run: |
          sed -i "s|image:.*|image: ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}|" k8s/manifests/deployment.yml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add k8s/manifests/deployment.yml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push
