apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: didle-app-ingress
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.albCertArn | quote }}
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: didle.shop,www.didle.shop
    alb.ingress.kubernetes.io/target-group-attributes: |
      stickiness.enabled=true
      stickiness.lb_cookie.duration_seconds=3600
    alb.ingress.kubernetes.io/target-type: ip
  
spec:
  rules:
  - host: didle.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: didle-app-service
            port:
              number: 8080
  - host: www.didle.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: didle-app-service
            port:
              number: 8080

