apiVersion: apps/v1
kind: Deployment
metadata:
  name: didle-app
  labels:
    app: didle-app
spec:
  progressDeadlineSeconds: 900  # 15분으로 확장
  replicas: 1  # 프리티어에서는 1개로 제한
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1       # 최대 추가 생성 허용 Pod 수
      maxUnavailable: 0  # 업데이트 중 다운 허용 Pod 수
  selector:
    matchLabels:
      app: didle-app
  template:
    metadata:
      labels:
        app: didle-app
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: didle-app
          image: 116981805975.dkr.ecr.us-east-2.amazonaws.com/hogeun-ecr-repo:20250318-761db9a
          imagePullPolicy: IfNotPresent  # 프리티어 트래픽 절약
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: jdbc-url
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db-password
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 45  # 프리티어 성능 고려
            periodSeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:  # 최소 요청량 (프리티어 최적화)
              memory: "256Mi"
              cpu: "250m"
            limits:    # 최대 한도 (과금 방지)
              memory: "512Mi"
              cpu: "500m"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
