apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    app: spring-app
spec:
  type: LoadBalancer
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  sessionAffinity: None
  externalTrafficPolicy: Cluster
