apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    app: didle-app
spec:
  type: LoadBalancer
  selector:
    app: didle-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  sessionAffinity: None  # 세션 유지 필요 시 ClientIP로 변경 가능
  externalTrafficPolicy: Cluster  # 클라이언트 IP 유지 필요 시 Local로 변경 가능
