replicaCount: 2
image:
  repository: 116981805975.dkr.ecr.us-east-2.amazonaws.com/hogeun-ecr-repo
  tag: 96aa800e78ce4f19fe8695fade6b1fb85a497785
service:
  type: ClusterIP
  port: 8080

aws:
  accessKey: ""
  secretKey: ""
  region: ""
  bucketName: ""


deployment:
  enabled: true
