replicaCount: 2
image:
  repository: 116981805975.dkr.ecr.us-east-1.amazonaws.com/hyeyoung-ecr-repo
  tag: 39a7d781ab1533dd4e8e54e24cffc057a1bbb454
service:
  type: ClusterIP
  port: 8080

deployment:
  enabled: true
