replicaCount: 2
image:
  repository: 116981805975.dkr.ecr.us-east-1.amazonaws.com/hyeyoung-ecr-repo
  tag: 47b2358bd9c8dc44b0489f77acba32fc779dcc61
service:
  type: ClusterIP
  port: 8080

deployment:
  enabled: true
