replicaCount: 2
image:
  repository: 116981805975.dkr.ecr.us-east-2.amazonaws.com/hogeun-ecr-repo
  tag: 9ab9a693f111966309f40ae17e5b6a95574bd008
service:
  type: ClusterIP
  port: 8080

aws:
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  bucketName: ${BUCKET_NAME}


deployment:
  enabled: true
