replicaCount: 2
image:
  repository: 116981805975.dkr.ecr.us-east-1.amazonaws.com/hyeyoung-ecr-repo
  tag: a82912ab1337ec62a5ddc5fe39744ae8ec7954f7
service:
  type: ClusterIP
  port: 8080

deployment:
  enabled: true
