replicaCount: 2
image:
  repository: 116981805975.dkr.ecr.us-east-1.amazonaws.com/hyeyoung-ecr-repo
  tag: ae95b3efa9b36ecdb39ed985d9746a2abe251f67
service:
  type: ClusterIP
  port: 8080

deployment:
  enabled: true
