replicaCount: 2
image:
  repository: 116981805975.dkr.ecr.us-east-1.amazonaws.com/hyeyoung-ecr-repo
  tag: f8e8b299a620b87fc7459da6668af11103179b7f
service:
  type: ClusterIP
  port: 8080

deployment:
  enabled: true
