replicaCount: 2
image:
  repository: 116981805975.dkr.ecr.us-east-2.amazonaws.com/hogeun-ecr-repo
  tag: 00d85ed99a40f61292519e7187c19230ff1dbf5f
service:
  type: ClusterIP
  port: 8080

aws:
  accessKey: ""
  secretKey: ""
  region: ""
  bucketName: ""


deployment:
  enabled: true
