replicaCount: 2
image:
  repository: 116981805975.dkr.ecr.us-east-2.amazonaws.com/hogeun-ecr-repo
  tag: 68ba6c0fac329313b6991b238b739f12bd28325a
service:
  type: ClusterIP
  port: 8080

aws:
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  bucketName: ${BUCKET_NAME}


deployment:
  enabled: true
