replicaCount: 2
image:
  repository: 116981805975.dkr.ecr.us-east-1.amazonaws.com/hyeyoung-ecr-repo
  tag: 37da23a843b804585659e148d8b9855ab540615a
service:
  type: ClusterIP
  port: 8080

deployment:
  enabled: true
