replicaCount: 2
image:
  repository: 116981805975.dkr.ecr.us-east-2.amazonaws.com/hogeun-ecr
  tag: 82045b493e39f6362b9c012a9d0ac969b384ea4c
service:
  type: ClusterIP
  port: 8080

aws:
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  bucketName: ${BUCKET_NAME}

deployment:
  enabled: true

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-2:116981805975:certificate/Z0806459397UC3SHTNFHF"
  hosts:
    - host: www.didle.com  # Route 53에 설정한 도메인으로 변경
      paths:
        - path: /
          pathType: Prefix
