
replicaCount: 2

image:
  repository: 116981805975.dkr.ecr.us-east-2.amazonaws.com/didle-ecr
<<<<<<< HEAD
  tag: 90bdf2b432b066c6648a0aeb1911b415d53f242f

=======
  tag: bdb8cb653bb2f750b1dba55be51b8ca89f58a2e2
>>>>>>> 6beab940309aa2a1dc9d13aae618a99ee805c7e7
service:
  type: ClusterIP
  port: 8080


aws:
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  bucketName: ${BUCKET_NAME}

deployment:
  enabled: true

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    external-dns.alpha.kubernetes.io/hostname: www.didle.shop

  hosts:
    - host: www.didle.shop
      paths:
        - path: /
          pathType: Prefix

albCertArn: "arn:aws:acm:us-east-2:116981805975:certificate/108ee2b1-927d-4bc7-aee5-a81485952987"
