name: Deploy After Terraform Apply

on:
  workflow_dispatch: # 수동 트리거

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: hogeun-ecr-repo
  EKS_CLUSTER: hogeun-eks-cluster
  K8S_NAMESPACE: default
  APP_NAME: didle-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # 1. AWS 권한 설정
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-session-name: GitHubActions-${{ github.run_id }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/cicd-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      # 2. EKS 클러스터 접근 설정
      - name: Configure EKS access
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ env.EKS_CLUSTER }}

      # 3. 쿠버네티스 배포
      - name: Deploy to EKS
        run: |
          cd didle/didle/k8s/manifests
          kustomize build . | kubectl apply -f - --validate=false
          kubectl rollout status deployment/${{ env.APP_NAME }} -n ${{ env.K8S_NAMESPACE }}
