name: Build and Push

permissions:
  id-token: write
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: read

on:
  workflow_dispatch:  # 수동 실행을 위한 트리거
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: hogeun-ecr-repo
  HELM_CHART_PATH: ./helm-charts/didle

jobs:
  build-and-push:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      deployments: write
      contents: write
      statuses: write
      actions: write
      checks: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/hogeun-cicd-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build with Gradle
        run: |
          cd didle/didle
          chmod +x ./gradlew
          ./gradlew build

          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

          echo $AWS_ACCESS_KEY_ID
          echo $AWS_SECRET_ACCESS_KEY

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG didle/didle
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Save image tag as artifact
        run: echo "${{ github.sha }}" > image_tag.txt

      - name: Update Helm chart
        run: |
          sed -i 's|repository:.*|repository: '${{ steps.login-ecr.outputs.registry }}'/'$ECR_REPOSITORY'|' $HELM_CHART_PATH/values.yaml
          sed -i 's|tag:.*|tag: '${{ github.sha }}'|' $HELM_CHART_PATH/values.yaml

      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add $HELM_CHART_PATH/values.yaml
          git commit -m "Update image tag" || exit 0
          git push
