name: Build and Push

permissions:
  id-token: write
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: read

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: hogeun-ecr-repo
  HELM_CHART_PATH: ./helm-charts/didle
  BUCKET_NAME: hogeun-bucket

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/hogeun-cicd-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build with Gradle
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
          BUCKET_NAME: ${{ env.BUCKET_NAME }}
        run: |
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
          echo "AWS_REGION=$AWS_REGION"
          echo "BUCKET_NAME=$BUCKET_NAME"

          cd didle/didle
          chmod +x ./gradlew
          ./gradlew build \
            -Dspring.cloud.aws.credentials.access-key=$AWS_ACCESS_KEY_ID \
            -Dspring.cloud.aws.credentials.secret-key=$AWS_SECRET_ACCESS_KEY \
            -Dspring.cloud.aws.region.static=${{ env.AWS_REGION }} \
            -Dspring.s3.bucket=${{ env.BUCKET_NAME }}

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG didle/didle
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Save image tag as artifact
        run: echo "${{ github.sha }}" > image_tag.txt

      - name: Update Helm chart
        run: |
          sed -i 's|repository:.*|repository: '${{ steps.login-ecr.outputs.registry }}'/'$ECR_REPOSITORY'|' $HELM_CHART_PATH/values.yaml
          sed -i 's|tag:.*|tag: '${{ github.sha }}'|' $HELM_CHART_PATH/values.yaml

      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add $HELM_CHART_PATH/values.yaml || exit 0
          git commit -m "Update image tag" || exit 0
          git push || exit 0
