name: Merge 후 자동 배포

on:
  push:
    branches:
      - main  # main 브랜치에 Push되면 실행 (Merge 후)

jobs:
  deploy:
    runs-on: ubuntu-latest  # 또는 self-hosted Runner
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: 빌드 실행
        run: npm run build

      - name: AWS S3에 배포
        run: aws s3 sync ./dist s3://my-website

