name: Build and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'didle/didle/**'

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: hogeun-ecr-repo
  EKS_CLUSTER: hogeun-eks-cluster
  K8S_NAMESPACE: default
  APP_NAME: didle-app

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 동적 이미지 태그 생성
      - name: Generate image tag
        id: tag
        run: |
          echo "TAG=$(date +%Y%m%d)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      # 3. AWS 권한 설정
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-session-name: GitHubActions-${{ github.run_id }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/cicd-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      # 4. ECR 로그인
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 5. 도커 이미지 빌드 및 푸시
      - name: Build and Push Docker Image
        run: |
          cd didle/didle
          export AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
          export TAG=${{ steps.tag.outputs.TAG }}
          docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-2.amazonaws.com/hogeun-ecr-repo:${TAG} .
          docker push ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-2.amazonaws.com/hogeun-ecr-repo:${TAG}

      # 6. Kustomize를 통한 매니페스트 업데이트
      - name: Update Kustomize configuration
        run: |
          cd didle/didle/k8s/manifests
          kustomize edit set image 116981805975.dkr.ecr.us-east-2.amazonaws.com/hogeun-ecr-repo:${{ steps.tag.outputs.TAG }}

      # 7. EKS 클러스터 접근 설정
      - name: Configure EKS access
        run: |
          aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ env.EKS_CLUSTER }}

      - name: Replace image tag in deployment.yml
        run: |
          cd didle/didle
          sed -i "s|PLACEHOLDER_IMAGE_TAG|116981805975.dkr.ecr.us-east-2.amazonaws.com/hogeun-ecr-repo:${{ steps.tag.outputs.TAG }}|g" deployment.yml

      # 8. 매니페스트 파일에서 ${TAG} 치환 및 배포
      - name: Deploy to EKS with envsubst
        run: |
          export TAG=${{ steps.tag.outputs.TAG }}
          cd didle/didle/k8s/manifests
          kustomize build . | envsubst | kubectl apply -f -
          kubectl rollout status deployment/${{ env.APP_NAME }} -n ${{ env.K8S_NAMESPACE }}
