name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push"]
    types:
      - completed

env:
  AWS_REGION: us-east-2
  EKS_CLUSTER: hogeun-eks-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/cicd-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks get-token --cluster-name ${{ env.EKS_CLUSTER }} | kubectl apply -f -

      - name: Deploy to ArgoCD
        run: |
          argocd app set didle-app --helm-set image.tag=${{ github.sha }}
          argocd app sync didle-app --prune
