name: PR 자동 테스트

on:
  pull_request:
    branches:
      - main  # main 브랜치로 PR이 생성될 때 실행

jobs:
  test:
    runs-on: self-hosted  # 직접 설치한 Rocky Linux 9 Runner에서 실행
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: Rocky Linux 9 환경 확인
        run: cat /etc/os-release

      - name: Node.js 설치
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: 의존성 설치
        run: npm install

      - name: 테스트 실행
        run: npm test

  docker-build:
    runs-on: self-hosted  # Rocky Linux 9에서 실행
    needs: test  # 테스트 성공 후 실행
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: Docker 설치 확인
        run: docker --version

      - name: Docker 이미지 빌드 테스트
        run: docker build -t my-app:test .

