name: PR 자동 테스트

on:
  pull_request:
    branches:
      - main  # main 브랜치로 PR이 생성될 때 실행

jobs:
  test:
    runs-on: self-hosted  # Rocky Linux 9에서 실행
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: Java 17 설치
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Eclipse Temurin (OpenJDK 17)
          java-version: '17'

      - name: Gradle 실행 권한 부여
        run: chmod +x gradlew

      - name: 프로젝트 빌드 (Gradle)
        run: ./gradlew build -x test  # 테스트 제외하고 빌드 (필요하면 -x test 제거)

      - name: 빌드된 JAR 파일 확인
        run: ls -l build/libs/*.jar

      - name: JAR 파일 이름 환경 변수 설정
        run: echo "JAR_FILE=$(ls build/libs/*.jar | head -n 1)" >> $GITHUB_ENV

  docker-build:
    runs-on: self-hosted  # Rocky Linux 9에서 실행
    needs: test  # 빌드 성공 후 실행
    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: Docker 설치 확인
        run: docker --version

      - name: Docker 이미지 빌드 테스트
        run: docker build --build-arg JAR_FILE=${{ env.JAR_FILE }} -t my-app:test .

