name: Self-hosted Runner Test

on:
  push:
    branches:
      - main  # main 브랜치에 push할 때 실행

jobs:
  test-runner:
    runs-on: self-hosted  # Self-hosted Runner에서 실행
    steps:
      - name: Checkout 코드
        uses: actions/checkout@v3

      - name: Self-hosted Runner 테스트 실행
        run: echo "GitHub Actions Self-hosted Runner 동작 확인!"

      - name: 현재 실행 중인 서버 정보 확인
        run: uname -a && whoami && pwd

